USE [master]
GO
/****** Object:  Database [ASPCRUD]    Script Date: 8/7/2019 8:11:43 PM ******/
CREATE DATABASE [ASPCRUD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ASPCRUD', FILENAME = N'F:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\ASPCRUD.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ASPCRUD_log', FILENAME = N'F:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\ASPCRUD_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [ASPCRUD] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ASPCRUD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ASPCRUD] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ASPCRUD] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ASPCRUD] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ASPCRUD] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ASPCRUD] SET ARITHABORT OFF 
GO
ALTER DATABASE [ASPCRUD] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ASPCRUD] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ASPCRUD] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ASPCRUD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ASPCRUD] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ASPCRUD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ASPCRUD] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ASPCRUD] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ASPCRUD] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ASPCRUD] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ASPCRUD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ASPCRUD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ASPCRUD] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ASPCRUD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ASPCRUD] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ASPCRUD] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ASPCRUD] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ASPCRUD] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ASPCRUD] SET  MULTI_USER 
GO
ALTER DATABASE [ASPCRUD] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ASPCRUD] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ASPCRUD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ASPCRUD] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [ASPCRUD] SET DELAYED_DURABILITY = DISABLED 
GO
USE [ASPCRUD]
GO
/****** Object:  Table [dbo].[Contact]    Script Date: 8/7/2019 8:11:43 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Contact](
	[ContactID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
	[Mobile] [varchar](50) NULL,
	[Address] [varchar](50) NULL,
 CONSTRAINT [PK_Contact] PRIMARY KEY CLUSTERED 
(
	[ContactID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  StoredProcedure [dbo].[ContactCreateOrUpdate]    Script Date: 8/7/2019 8:11:43 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[ContactCreateOrUpdate]
@ContactID int,
@Name varchar(50),
@Mobile varchar(50),
@Address varchar(250)
AS
BEGIN
IF(@ContactID=0)
	BEGIN
	INSERT INTO Contact(Name, Mobile, Address)
	VALUES(@Name, @Mobile, @Address)
	END
ELSE
	BEGIN
	UPDATE Contact
	SET 
		Name = @Name,
		Mobile = @Mobile,
		Address= @Address
	WHERE ContactID = @ContactID
	END
END
GO
/****** Object:  StoredProcedure [dbo].[ContactDeleteByID]    Script Date: 8/7/2019 8:11:43 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[ContactDeleteByID]
@ContactID int
AS
	BEGIN
	DELETE FROM Contact
	WHERE ContactID=@ContactID
	END
GO
/****** Object:  StoredProcedure [dbo].[ContactViewAll]    Script Date: 8/7/2019 8:11:43 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[ContactViewAll]
AS
	BEGIN
	SELECT * FROM Contact
	END
GO
/****** Object:  StoredProcedure [dbo].[ContactViewByID]    Script Date: 8/7/2019 8:11:43 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[ContactViewByID]
@ContactID int
AS
	BEGIN
	SELECT * FROM Contact
	WHERE ContactID=@ContactID
	END
GO
USE [master]
GO
ALTER DATABASE [ASPCRUD] SET  READ_WRITE 
GO
